joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.59
    has_acceleration_limits: true
    max_acceleration: 2.5
    has_jerk_limits: true
    max_jerk: 42
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.59
    has_acceleration_limits: true
    max_acceleration: 1.8
    has_jerk_limits: true
    max_jerk: 42
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.59
    has_acceleration_limits: true
    max_acceleration: 2.5
    has_jerk_limits: true
    max_jerk: 42
  joint_4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 3.5
    has_jerk_limits: true
    max_jerk: 42
  joint_5:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
    has_jerk_limits: true
    max_jerk: 42
  joint_6:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 5
    has_jerk_limits: true
    max_jerk: 42
