controller_manager:
  ros__parameters:
    update_rate: 8000

    i608_arm_controller:
      type: icnc_controllers/IcncJointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

i608_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    joint_limits:
      joint_1:
        has_velocity_limits: true
        max_velocity: 2.59
        min_velocity: -2.59
        has_acceleration_limits: true
        max_acceleration: 2.5
        has_jerk_limits: true
        max_jerk: 400.0
      joint_2:
        has_velocity_limits: true
        max_velocity: 2.59
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 1.8
        has_jerk_limits: true
        max_jerk: 400.0
      joint_3:
        has_velocity_limits: true
        max_velocity: 2.59
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 2.5
        has_jerk_limits: true
        max_jerk: 400.0
      joint_4:
        has_velocity_limits: true
        max_velocity: 5.0
        min_velocity: -5.0
        has_acceleration_limits: true
        max_acceleration: 3.5
        has_jerk_limits: true
        max_jerk: 1000.0
      joint_5:
        has_velocity_limits: true
        max_velocity: 5.0
        min_velocity: -5.0
        has_acceleration_limits: true
        max_acceleration: 5.0
        has_jerk_limits: true
        max_jerk: 1000.0
      joint_6:
        has_velocity_limits: true
        max_velocity: 5.0
        min_velocity: -5.0
        has_acceleration_limits: true
        max_acceleration: 5.0
        has_jerk_limits: true
        max_jerk: 1000.0
