controller_manager:
  ros__parameters:
    update_rate: 8000

    i608_arm_controller:
      type: icnc_controllers/I608JointController

    joint_state_controller:
      type: joint_state_controller/JointStateBroadcaster

i608_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
